# Generated by Django 4.1.7 on 2023-03-04 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=65, verbose_name='Full name')),
                ('name_scheme', models.CharField(max_length=40, verbose_name='Name of scheme')),
                ('job', models.CharField(max_length=100, verbose_name='Job')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('domain_name', models.CharField(max_length=100, verbose_name='Domain')),
                ('company_name', models.CharField(max_length=30, verbose_name='Company name')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18),
                                                        django.core.validators.MaxValueValidator(65)])),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
